//! Renders usage data as compact markdown for LLM analysis. The output is
//! designed to be pasted (or fetched) into a Claude session that then
//! suggests workflow improvements — dense tables, explicit friction signals,
//! no prose padding.

const std = @import("std");
const Allocator = std.mem.Allocator;
const stats = @import("stats.zig");
const index_mod = @import("index.zig");
const time_mod = @import("time.zig");

pub const max_prompt_samples = 10;
pub const max_prompt_sample_len = 200;

pub const Input = struct {
    report: stats.Report,
    sessions: []const index_mod.SessionSummary,
    /// Most recent user prompts, oldest first.
    prompt_samples: []const []const u8,
    tool_version: []const u8,
};

/// Builds the markdown digest. Arena-allocated.
pub fn build(arena: Allocator, input: Input) Allocator.Error![]const u8 {
    var out: std.ArrayList(u8) = .empty;
    const w = &out;

    try header(w, arena, input);
    try totalsSection(w, arena, input.report);
    try dailySection(w, arena, input.report);
    try projectsSection(w, arena, input.report);
    try toolsSection(w, arena, input.report);
    try frictionSection(w, arena, input);
    try promptSamplesSection(w, arena, input.prompt_samples);
    try adviceRequest(w, arena);
    return out.toOwnedSlice(arena);
}

fn header(w: *std.ArrayList(u8), arena: Allocator, input: Input) Allocator.Error!void {
    var date_buf: [10]u8 = undefined;
    const today = stats.dayKeyFromMs(input.report.generated_at_ms) orelse 0;
    try w.print(arena,
        \\# Claude Code usage digest
        \\
        \\Generated by claudiusz {s} on {s} (UTC), window: last {d} days.
        \\This document summarizes how a developer uses Claude Code across projects.
        \\
        \\
    , .{ input.tool_version, stats.formatDayKey(&date_buf, today), input.report.range_days });
}

fn totalsSection(w: *std.ArrayList(u8), arena: Allocator, report: stats.Report) Allocator.Error!void {
    const t = report.totals;
    try w.print(arena,
        \\## Totals
        \\
        \\- prompts: {d}
        \\- tool calls: {d} ({d} failed)
        \\- tokens: {d} in / {d} out / {d} cache-read / {d} cache-write
        \\
        \\
    , .{
        t.prompts,               t.tool_calls,    t.failures,
        t.tokens.input,          t.tokens.output, t.tokens.cache_read,
        t.tokens.cache_creation,
    });
}

fn dailySection(w: *std.ArrayList(u8), arena: Allocator, report: stats.Report) Allocator.Error!void {
    if (report.days.len == 0) return;
    try w.appendSlice(arena, "## Per day\n\n| date | prompts | tool calls | failures | tokens out |\n|---|---|---|---|---|\n");
    for (report.days) |day| {
        try w.print(arena, "| {s} | {d} | {d} | {d} | {d} |\n", .{
            day.date, day.prompts, day.tool_calls, day.failures, day.tokens.output,
        });
    }
    try w.appendSlice(arena, "\n");
}

fn projectsSection(w: *std.ArrayList(u8), arena: Allocator, report: stats.Report) Allocator.Error!void {
    if (report.top_projects.len == 0) return;
    try w.appendSlice(arena, "## Projects (active in window)\n\n| project | sessions | prompts | tool calls | failures | hook errors | tokens out |\n|---|---|---|---|---|---|---|\n");
    for (report.top_projects[0..@min(report.top_projects.len, 15)]) |p| {
        try w.print(arena, "| {s} | {d} | {d} | {d} | {d} | {d} | {d} |\n", .{
            p.project, p.sessions, p.prompts, p.tool_calls, p.failures, p.hook_errors, p.tokens.output,
        });
    }
    try w.appendSlice(arena, "\n");
}

fn toolsSection(w: *std.ArrayList(u8), arena: Allocator, report: stats.Report) Allocator.Error!void {
    if (report.top_tools.len == 0) return;
    try w.appendSlice(arena, "## Top tools\n\n");
    for (report.top_tools[0..@min(report.top_tools.len, 12)]) |tool| {
        try w.print(arena, "- {s}: {d}\n", .{ tool.name, tool.count });
    }
    try w.appendSlice(arena, "\n");
}

fn frictionSection(w: *std.ArrayList(u8), arena: Allocator, input: Input) Allocator.Error!void {
    try w.appendSlice(arena, "## Friction signals\n\n");
    var found = false;

    for (input.sessions) |s| {
        if (std.mem.eql(u8, s.status, "waiting_for_user")) {
            try w.print(arena, "- session in `{s}` is waiting on the user: {s}\n", .{ s.project, s.waiting_for });
            found = true;
        }
    }
    for (input.report.top_projects) |p| {
        if (p.hook_errors > 0) {
            try w.print(arena, "- `{s}`: {d} hook errors (a configured hook keeps failing)\n", .{ p.project, p.hook_errors });
            found = true;
        }
        if (p.tool_calls > 20 and p.failures * 5 >= p.tool_calls) {
            try w.print(arena, "- `{s}`: high tool failure rate ({d}/{d})\n", .{ p.project, p.failures, p.tool_calls });
            found = true;
        }
    }
    if (!found) try w.appendSlice(arena, "- none detected\n");
    try w.appendSlice(arena, "\n");
}

fn promptSamplesSection(w: *std.ArrayList(u8), arena: Allocator, samples: []const []const u8) Allocator.Error!void {
    if (samples.len == 0) return;
    try w.appendSlice(arena, "## Recent prompt samples (verbatim, truncated)\n\n");
    const first = samples.len -| max_prompt_samples;
    for (samples[first..]) |sample| {
        const line = firstLine(sample);
        const cut = @min(line.len, max_prompt_sample_len);
        try w.print(arena, "- \"{s}{s}\"\n", .{ line[0..cut], if (cut < sample.len) "…" else "" });
    }
    try w.appendSlice(arena, "\n");
}

fn adviceRequest(w: *std.ArrayList(u8), arena: Allocator) Allocator.Error!void {
    try w.appendSlice(arena,
        \\## Analysis request
        \\
        \\Based on the data above, identify: (1) workflow inefficiencies (prompt
        \\style, missing project context files, repeated friction), (2) projects
        \\that would benefit from configuration changes (CLAUDE.md, permissions,
        \\hooks), (3) concrete, prioritized suggestions. Reference the specific
        \\numbers that motivated each suggestion.
        \\
    );
}

fn firstLine(text: []const u8) []const u8 {
    const end = std.mem.indexOfScalar(u8, text, '\n') orelse text.len;
    return text[0..end];
}

// --- tests ---------------------------------------------------------------

const testing = std.testing;

test "digest renders all sections from a populated report" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    var days = [_]stats.DayRow{
        .{ .date = "2026-07-06", .day_key = 20_640, .prompts = 12, .tool_calls = 80, .failures = 2, .tokens = .{ .output = 50_000 } },
    };
    var tools = [_]index_mod.ToolCount{.{ .name = "Bash", .count = 44 }};
    var projects = [_]stats.ProjectRow{
        .{ .project = "webshop", .sessions = 2, .prompts = 12, .tool_calls = 80, .failures = 2, .hook_errors = 3, .tokens = .{ .output = 50_000 } },
    };
    const sessions = [_]index_mod.SessionSummary{};
    const samples = [_][]const u8{ "fix the login bug", "add dark mode\nwith details" };

    const markdown = try build(arena, .{
        .report = .{
            .range_days = 7,
            .generated_at_ms = 1_783_450_486_347,
            .totals = .{ .prompts = 12, .tool_calls = 80, .failures = 2, .tokens = .{ .input = 100, .output = 50_000 } },
            .days = &days,
            .top_tools = &tools,
            .top_projects = &projects,
            .hour_prompts = @splat(0),
        },
        .sessions = &sessions,
        .prompt_samples = &samples,
        .tool_version = "0.1.0",
    });

    try testing.expect(std.mem.indexOf(u8, markdown, "# Claude Code usage digest") != null);
    try testing.expect(std.mem.indexOf(u8, markdown, "| 2026-07-06 | 12 | 80 | 2 | 50000 |") != null);
    try testing.expect(std.mem.indexOf(u8, markdown, "- Bash: 44") != null);
    try testing.expect(std.mem.indexOf(u8, markdown, "3 hook errors") != null);
    try testing.expect(std.mem.indexOf(u8, markdown, "\"fix the login bug\"") != null);
    try testing.expect(std.mem.indexOf(u8, markdown, "\"add dark mode…\"") != null);
    try testing.expect(std.mem.indexOf(u8, markdown, "## Analysis request") != null);
}

test "digest with empty data still renders totals and request" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const markdown = try build(arena, .{
        .report = .{
            .range_days = 7,
            .generated_at_ms = 0,
            .totals = .{},
            .days = &.{},
            .top_tools = &.{},
            .top_projects = &.{},
            .hour_prompts = @splat(0),
        },
        .sessions = &.{},
        .prompt_samples = &.{},
        .tool_version = "0.1.0",
    });
    try testing.expect(std.mem.indexOf(u8, markdown, "- none detected") != null);
    try testing.expect(std.mem.indexOf(u8, markdown, "## Analysis request") != null);
}
